/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:64a05e97-05ce-4fd3-8f6a-72daf9bde27f",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_XHlgNSA6P",
    "aws_user_pools_web_client_id": "6qvosvpher6r31qsbv8p2i30um",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://xejmqsl3hfhvphz7b6prhrelge.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-c2f6b4putjfxffdqetgh7lbwbu",
    "aws_user_files_s3_bucket": "amplifyappae732637f29043d4ad40da6e52512924135430-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
